"""init schema

Revision ID: 55b74d93d86f
Revises: 
Create Date: 2026-06-21 09:16:07.778153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55b74d93d86f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_insights',
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('summary', sa.String(length=4096), nullable=False),
    sa.Column('details_json', sa.String(length=8192), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_insights_report_date'), 'ai_insights', ['report_date'], unique=False)
    op.create_table('communities',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('category', sa.Enum('MUSIC', 'SPORT', 'WALKS', 'CINEMA', 'GAMES', 'DANCING', 'FOOD', 'BUSINESS', 'IT', 'ART', 'NIGHT_CITY', 'TRAVEL', 'ADULT_18', 'QUICK_MEETUPS', 'VOICE_CHAT', name='interestcategory', native_enum=False, length=32), nullable=False),
    sa.Column('name_ru', sa.String(length=128), nullable=False),
    sa.Column('name_en', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communities_category'), 'communities', ['category'], unique=False)
    op.create_index(op.f('ix_communities_code'), 'communities', ['code'], unique=True)
    op.create_table('contests',
    sa.Column('type', sa.Enum('BEST_PHOTO', 'BEST_DIALOG', 'JAZZ_EVENING', 'DISTRICT_WALK', 'SPEED_MATCH', 'VOICE_EVENING', 'CUSTOM', name='contesttype', native_enum=False, length=24), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contests_city'), 'contests', ['city'], unique=False)
    op.create_index(op.f('ix_contests_is_active'), 'contests', ['is_active'], unique=False)
    op.create_table('interests',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('category', sa.Enum('MUSIC', 'SPORT', 'WALKS', 'CINEMA', 'GAMES', 'DANCING', 'FOOD', 'BUSINESS', 'IT', 'ART', 'NIGHT_CITY', 'TRAVEL', 'ADULT_18', 'QUICK_MEETUPS', 'VOICE_CHAT', name='interestcategory', native_enum=False, length=32), nullable=False),
    sa.Column('name_ru', sa.String(length=64), nullable=False),
    sa.Column('name_en', sa.String(length=64), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interests_category'), 'interests', ['category'], unique=False)
    op.create_index(op.f('ix_interests_code'), 'interests', ['code'], unique=True)
    op.create_table('system_metrics',
    sa.Column('metric_name', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('dimension', sa.String(length=64), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_metrics_metric_name'), 'system_metrics', ['metric_name'], unique=False)
    op.create_table('users',
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('state', sa.Enum('NEW', 'PROFILE_CREATION', 'VERIFICATION', 'ACTIVE_SEARCH', 'ACTIVE_CHAT', 'BUFFER_MATCH', 'PAUSE', 'INACTIVE', 'LIMITED', 'BANNED_BY_SYSTEM', name='userstate', native_enum=False, length=32), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('spam_score', sa.Float(), nullable=False),
    sa.Column('referral_code', sa.String(length=16), nullable=False),
    sa.Column('referred_by_id', sa.BigInteger(), nullable=True),
    sa.Column('device_fingerprint', sa.String(length=128), nullable=True),
    sa.Column('last_active_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['referred_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_device_fingerprint'), 'users', ['device_fingerprint'], unique=False)
    op.create_index(op.f('ix_users_last_active_at'), 'users', ['last_active_at'], unique=False)
    op.create_index(op.f('ix_users_referral_code'), 'users', ['referral_code'], unique=True)
    op.create_index(op.f('ix_users_risk_score'), 'users', ['risk_score'], unique=False)
    op.create_index(op.f('ix_users_state'), 'users', ['state'], unique=False)
    op.create_index('ix_users_state_last_active', 'users', ['state', 'last_active_at'], unique=False)
    op.create_index(op.f('ix_users_tg_id'), 'users', ['tg_id'], unique=True)
    op.create_table('activity_scores',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('period', sa.String(length=16), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_scores_user_id'), 'activity_scores', ['user_id'], unique=False)
    op.create_table('community_members',
    sa.Column('community_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('community_id', 'user_id')
    )
    op.create_table('contest_entries',
    sa.Column('contest_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('payload', sa.String(length=512), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contest_id'], ['contests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contest_entries_contest_id'), 'contest_entries', ['contest_id'], unique=False)
    op.create_index(op.f('ix_contest_entries_user_id'), 'contest_entries', ['user_id'], unique=False)
    op.create_table('event_logs',
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.String(length=2048), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_logs_event_type'), 'event_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_event_logs_user_id'), 'event_logs', ['user_id'], unique=False)
    op.create_table('likes',
    sa.Column('from_user_id', sa.BigInteger(), nullable=False),
    sa.Column('to_user_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_user_id', 'to_user_id', name='uq_like_pair')
    )
    op.create_index(op.f('ix_likes_from_user_id'), 'likes', ['from_user_id'], unique=False)
    op.create_index(op.f('ix_likes_to_user_id'), 'likes', ['to_user_id'], unique=False)
    op.create_table('matches',
    sa.Column('user_a_id', sa.BigInteger(), nullable=False),
    sa.Column('user_b_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'BUFFER', 'CLOSED', name='matchstatus', native_enum=False, length=16), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_a_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_b_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_status'), 'matches', ['status'], unique=False)
    op.create_index(op.f('ix_matches_user_a_id'), 'matches', ['user_a_id'], unique=False)
    op.create_index(op.f('ix_matches_user_b_id'), 'matches', ['user_b_id'], unique=False)
    op.create_index('ix_matches_users', 'matches', ['user_a_id', 'user_b_id'], unique=False)
    op.create_table('payments',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.Enum('TELEGRAM_STARS', 'STRIPE', 'LIQPAY', 'FONDY', 'WAYFORPAY', name='paymentprovidername', native_enum=False, length=32), nullable=False),
    sa.Column('feature', sa.Enum('EXTEND_CHAT', 'EXTRA_LIKES', 'EARLY_ACCESS', 'EXTENDED_RADIUS', 'CREATE_COMMUNITY_EVENT', 'PAID_CONTEST_ENTRY', 'INVISIBLE_PAUSE', 'EXTENDED_STATS', 'DONATION', name='paidfeature', native_enum=False, length=32), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', 'REFUNDED', name='paymentstatus', native_enum=False, length=16), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('payload', sa.String(length=512), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_external_id'), 'payments', ['external_id'], unique=False)
    op.create_index(op.f('ix_payments_feature'), 'payments', ['feature'], unique=False)
    op.create_index(op.f('ix_payments_provider'), 'payments', ['provider'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_table('photos',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_file_id', sa.String(length=256), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('phash', sa.String(length=64), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_flagged_duplicate', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photos_phash'), 'photos', ['phash'], unique=False)
    op.create_index(op.f('ix_photos_sha256_hash'), 'photos', ['sha256_hash'], unique=False)
    op.create_index(op.f('ix_photos_user_id'), 'photos', ['user_id'], unique=False)
    op.create_table('profiles',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('district', sa.String(length=64), nullable=True),
    sa.Column('geo_lat', sa.Float(), nullable=True),
    sa.Column('geo_lon', sa.Float(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender', native_enum=False, length=16), nullable=False),
    sa.Column('seeking_gender', sa.Enum('MALE', 'FEMALE', 'ANY', name='seekinggender', native_enum=False, length=16), nullable=False),
    sa.Column('goal', sa.Enum('COMMUNICATION', 'DATE', 'INTIMATE', 'REGULAR', 'FRIENDSHIP', 'INTERESTS', 'EVENTS', name='goal', native_enum=False, length=16), nullable=False),
    sa.Column('radius_km', sa.Integer(), nullable=False),
    sa.Column('bio', sa.String(length=280), nullable=True),
    sa.Column('activity_score', sa.Float(), nullable=False),
    sa.Column('behavior_rating', sa.Float(), nullable=False),
    sa.Column('incoming_counter', sa.Integer(), nullable=False),
    sa.Column('incoming_counter_reset_at', sa.DateTime(), nullable=False),
    sa.Column('last_dialog_at', sa.DateTime(), nullable=True),
    sa.Column('is_invisible_pause', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_profiles_activity_score'), 'profiles', ['activity_score'], unique=False)
    op.create_index(op.f('ix_profiles_city'), 'profiles', ['city'], unique=False)
    op.create_index('ix_profiles_city_district_goal', 'profiles', ['city', 'district', 'goal'], unique=False)
    op.create_index(op.f('ix_profiles_district'), 'profiles', ['district'], unique=False)
    op.create_index(op.f('ix_profiles_goal'), 'profiles', ['goal'], unique=False)
    op.create_index(op.f('ix_profiles_incoming_counter'), 'profiles', ['incoming_counter'], unique=False)
    op.create_table('referrals',
    sa.Column('referrer_id', sa.BigInteger(), nullable=False),
    sa.Column('referred_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVATED', 'REJECTED', name='referralstatus', native_enum=False, length=16), nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('antifraud_note', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['referred_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referred_id', name='uq_referral_referred_once')
    )
    op.create_index(op.f('ix_referrals_referred_id'), 'referrals', ['referred_id'], unique=False)
    op.create_index(op.f('ix_referrals_referrer_id'), 'referrals', ['referrer_id'], unique=False)
    op.create_index(op.f('ix_referrals_status'), 'referrals', ['status'], unique=False)
    op.create_table('verifications',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('NONE', 'PENDING', 'APPROVED', 'REJECTED', name='verificationstatus', native_enum=False, length=16), nullable=False),
    sa.Column('method', sa.Enum('SELFIE_GESTURE', 'SHORT_VIDEO', name='verificationmethod', native_enum=False, length=24), nullable=True),
    sa.Column('gesture_code', sa.String(length=32), nullable=True),
    sa.Column('submitted_file_hash', sa.String(length=64), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewer_note', sa.String(length=256), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_verifications_status'), 'verifications', ['status'], unique=False)
    op.create_table('chats',
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('user_a_id', sa.BigInteger(), nullable=False),
    sa.Column('user_b_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'BUFFER', 'CLOSED', name='chatstatus', native_enum=False, length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('extended_count', sa.Integer(), nullable=False),
    sa.Column('user_a_wants_extend', sa.Boolean(), nullable=False),
    sa.Column('user_b_wants_extend', sa.Boolean(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('closed_reason', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_a_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_b_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id')
    )
    op.create_index(op.f('ix_chats_expires_at'), 'chats', ['expires_at'], unique=False)
    op.create_index(op.f('ix_chats_last_message_at'), 'chats', ['last_message_at'], unique=False)
    op.create_index(op.f('ix_chats_status'), 'chats', ['status'], unique=False)
    op.create_index(op.f('ix_chats_user_a_id'), 'chats', ['user_a_id'], unique=False)
    op.create_index(op.f('ix_chats_user_b_id'), 'chats', ['user_b_id'], unique=False)
    op.create_table('user_interests',
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('interest_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['interest_id'], ['interests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', 'interest_id')
    )
    op.create_table('messages',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('sender_id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.String(length=4096), nullable=False),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_chat_id'), 'messages', ['chat_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.create_table('moderation_queue',
    sa.Column('signal_type', sa.Enum('DANGER_BUTTON', 'RISK_KEYWORDS', 'REPEAT_PHOTO', 'SPAM_PATTERN', name='moderationsignaltype', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'REVIEWING', 'RESOLVED', 'DISMISSED', name='moderationstatus', native_enum=False, length=16), nullable=False),
    sa.Column('reporter_user_id', sa.BigInteger(), nullable=True),
    sa.Column('target_user_id', sa.BigInteger(), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('reason', sa.String(length=512), nullable=True),
    sa.Column('resolution_note', sa.String(length=512), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['reporter_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moderation_queue_signal_type'), 'moderation_queue', ['signal_type'], unique=False)
    op.create_index(op.f('ix_moderation_queue_status'), 'moderation_queue', ['status'], unique=False)
    op.create_index(op.f('ix_moderation_queue_target_user_id'), 'moderation_queue', ['target_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_moderation_queue_target_user_id'), table_name='moderation_queue')
    op.drop_index(op.f('ix_moderation_queue_status'), table_name='moderation_queue')
    op.drop_index(op.f('ix_moderation_queue_signal_type'), table_name='moderation_queue')
    op.drop_table('moderation_queue')
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_chat_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_table('user_interests')
    op.drop_index(op.f('ix_chats_user_b_id'), table_name='chats')
    op.drop_index(op.f('ix_chats_user_a_id'), table_name='chats')
    op.drop_index(op.f('ix_chats_status'), table_name='chats')
    op.drop_index(op.f('ix_chats_last_message_at'), table_name='chats')
    op.drop_index(op.f('ix_chats_expires_at'), table_name='chats')
    op.drop_table('chats')
    op.drop_index(op.f('ix_verifications_status'), table_name='verifications')
    op.drop_table('verifications')
    op.drop_index(op.f('ix_referrals_status'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referrer_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referred_id'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_index(op.f('ix_profiles_incoming_counter'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_goal'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_district'), table_name='profiles')
    op.drop_index('ix_profiles_city_district_goal', table_name='profiles')
    op.drop_index(op.f('ix_profiles_city'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_activity_score'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_photos_user_id'), table_name='photos')
    op.drop_index(op.f('ix_photos_sha256_hash'), table_name='photos')
    op.drop_index(op.f('ix_photos_phash'), table_name='photos')
    op.drop_table('photos')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_provider'), table_name='payments')
    op.drop_index(op.f('ix_payments_feature'), table_name='payments')
    op.drop_index(op.f('ix_payments_external_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_matches_users', table_name='matches')
    op.drop_index(op.f('ix_matches_user_b_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_user_a_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_status'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_likes_to_user_id'), table_name='likes')
    op.drop_index(op.f('ix_likes_from_user_id'), table_name='likes')
    op.drop_table('likes')
    op.drop_index(op.f('ix_event_logs_user_id'), table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_event_type'), table_name='event_logs')
    op.drop_table('event_logs')
    op.drop_index(op.f('ix_contest_entries_user_id'), table_name='contest_entries')
    op.drop_index(op.f('ix_contest_entries_contest_id'), table_name='contest_entries')
    op.drop_table('contest_entries')
    op.drop_table('community_members')
    op.drop_index(op.f('ix_activity_scores_user_id'), table_name='activity_scores')
    op.drop_table('activity_scores')
    op.drop_index(op.f('ix_users_tg_id'), table_name='users')
    op.drop_index('ix_users_state_last_active', table_name='users')
    op.drop_index(op.f('ix_users_state'), table_name='users')
    op.drop_index(op.f('ix_users_risk_score'), table_name='users')
    op.drop_index(op.f('ix_users_referral_code'), table_name='users')
    op.drop_index(op.f('ix_users_last_active_at'), table_name='users')
    op.drop_index(op.f('ix_users_device_fingerprint'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_metrics_metric_name'), table_name='system_metrics')
    op.drop_table('system_metrics')
    op.drop_index(op.f('ix_interests_code'), table_name='interests')
    op.drop_index(op.f('ix_interests_category'), table_name='interests')
    op.drop_table('interests')
    op.drop_index(op.f('ix_contests_is_active'), table_name='contests')
    op.drop_index(op.f('ix_contests_city'), table_name='contests')
    op.drop_table('contests')
    op.drop_index(op.f('ix_communities_code'), table_name='communities')
    op.drop_index(op.f('ix_communities_category'), table_name='communities')
    op.drop_table('communities')
    op.drop_index(op.f('ix_ai_insights_report_date'), table_name='ai_insights')
    op.drop_table('ai_insights')
    # ### end Alembic commands ###
